# shrimpslayer_net
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShrimpslayerNet
  # All configuration including auth info and base URI for the API access
  # are configured in this class.
  class Configuration
    # The base Uri for API calls
    @base_uri = 'http://shrimpslayer.net/api'

    # The attribute accessors for public properties.
    class << self
      attr_accessor :array_serialization
      attr_accessor :base_uri
    end
  end
end
