# shrimpslayer_net
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShrimpslayerNet
  #  shrimpslayer_net client class.
  class ShrimpslayerNetClient
    # Singleton access to shrimp controller.
    # @return [ShrimpController] Returns the controller instance.
    def shrimp
      ShrimpController.instance
    end

    # Returns the configuration class for easy access.
    # @return [Configuration] Returns the actual configuration class.
    def config
      Configuration
    end
  end
end
