# shrimpslayer_net
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
require 'json'
require 'faraday'
require 'certifi'
require 'logging'

require_relative 'shrimpslayer_net/api_helper.rb'
require_relative 'shrimpslayer_net/shrimpslayer_net_client.rb'

# Http
require_relative 'shrimpslayer_net/http/http_call_back.rb'
require_relative 'shrimpslayer_net/http/http_client.rb'
require_relative 'shrimpslayer_net/http/http_method_enum.rb'
require_relative 'shrimpslayer_net/http/http_request.rb'
require_relative 'shrimpslayer_net/http/http_response.rb'
require_relative 'shrimpslayer_net/http/http_context.rb'
require_relative 'shrimpslayer_net/http/faraday_client.rb'

# Models
require_relative 'shrimpslayer_net/models/base_model.rb'

# Exceptions
require_relative 'shrimpslayer_net/exceptions/api_exception.rb'

require_relative 'shrimpslayer_net/configuration.rb'

# Controllers
require_relative 'shrimpslayer_net/controllers/base_controller.rb'
require_relative 'shrimpslayer_net/controllers/shrimp_controller.rb'
