# shrimpslayer_net
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShrimpslayerNet
  # ShrimpController
  class ShrimpController < BaseController
    @instance = ShrimpController.new

    class << self
      attr_accessor :instance
    end

    def instance
      self.class.instance
    end

    # Collect params
    # @param [String] operation Required parameter: Example:
    # @return String response from the API call
    def get_https_shrimpslayer_net(operation)
      # Prepare query url.
      _path_url = '/{operation}'
      _path_url = APIHelper.append_url_with_template_parameters(
        _path_url,
        'operation' => operation
      )
      _query_builder = Configuration.base_uri.dup
      _query_builder << _path_url
      _query_url = APIHelper.clean_url _query_builder

      # Prepare and execute HttpRequest.
      _request = @http_client.get(
        _query_url
      )
      _context = execute_request(_request)
      validate_response(_context)

      # Return appropriate response type.
      _context.response.raw_body
    end
  end
end
